version: "3.3"

services:
  backend-policy:
    image: ${DOCKER_REG}${DOCKER_REPO}${APP_NAME}:${DOCKER_TAG}
    build:
      context: ./backend/.
    container_name: backend-policy
    depends_on:
      - db-policy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-policy:5432/test_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=30a301d7257
    ports:
      - '8085:8080'
    restart: unless-stopped
    networks:
      - shared-net
    labels:
      io.portainer.accesscontrol.teams: skillab-all

  db-policy:
    image: postgres:14.7
    container_name: db-policy
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 30a301d7257
      POSTGRES_DB: test_db
    volumes:
       - policy_postgresql_data:/var/lib/postgresql/data
    ports:
      - '5455:5432'
    restart: unless-stopped
    networks:
      - shared-net
    labels:
      io.portainer.accesscontrol.teams: skillab-all

  # jbpm-policy:
  #   #image: jboss/jbpm-server-full:7.61.0.Final
  #   image: nikosnikolaidis/jbpm-allowframes:7.61.0.Final
  jbpm-policy:
    image: nikosnikolaidis/jbpm-allowframes:7.61.0.Final
    container_name: jbpm-policy
    environment:
      - JBPM_DB_DRIVER=postgres
      - JBPM_DB_HOST=jbpm-postgres-policy
      - JBPM_DB_NAME=jbpm
      - JBPM_DB_USER=jbpm
      - JBPM_DB_PASSWORD=jbpm
      - KIE_SERVER_LOCATION=https://portal.skillab-project.eu/kie-server/services/rest/server
    depends_on:
      - jbpm-postgres-policy
    ports:
      - '8080:8080'
    networks:
      - shared-net

  jbpm-postgres-policy:
    image: postgres:14.7
    container_name: jbpm-postgres-policy
    environment:
      POSTGRES_DB: jbpm
      POSTGRES_USER: jbpm
      POSTGRES_PASSWORD: jbpm
    volumes:
      - policy_postgres_db:/var/lib/postgresql/data
    networks:
      - shared-net
  

volumes:
  policy_postgresql_data:
    labels:
      io.portainer.accesscontrol.teams: skillab-all
  policy_postgres_db:
    labels:
      io.portainer.accesscontrol.teams: skillab-all
  niogit:
    labels:
      io.portainer.accesscontrol.teams: skillab-all

networks:
  shared-net:
    external: true
